### ISSUE TITLE
Railing

### ISSUE THREAD

**Issue by ost-ing** [hugelton/OpenTanz#1]
Hey, thanks for making this. I was wondering about the railing screw holes. Are the holes threaded? Or does the M3 screw into the plastic material directly? Or somehow else? 

Thanks!

**Comment by kurogedelic** [comment]
it is designed to be screwed directly into 3D printed.
just a concept like this:
https://www.thingiverse.com/thing:4863118

**Comment by ost-ing** [comment]
@kurogedelic Great - thanks!
